# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - deploy

resources:
  - repo: self

variables:
  tag: "$(image_name)"
  DOCKER_BUILDKIT: 1

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: Docker@2
            displayName: Build an image
            inputs:
              args: GITHUB_AUTH=$(GITHUB_AUTH)
              command: build
              dockerfile: "$(Build.SourcesDirectory)/Dockerfile"
              tags: |
                $(tag)
          - task: Docker@2
            inputs:
              containerRegistry: 'nziswano docker registry'
              repository: $(image_name)
              command: 'push'
              tags: |
                $(tag)
