version: "3"
services:
  web:
    image: nginx:1.17
    depends_on:
      - wordpress
      - db
    ports:
      - "7000:80"
    volumes:
      - ./site/www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  wordpress:
    image: paseo:wordpress
    build:
      context: .
      args:
        GITHUB_AUTH: ${COMPOSER_AUTH}
    container_name: wordpress
    depends_on:
      - db
    volumes:
      - ./site/www:/var/www/html
      - ./site/sockets:/var/run/mysqld
    env_file: .env.docker
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      AUTH_KEY: ${AUTH_KEY}
      SECURE_AUTH_KEY: ${SECURE_AUTH_KEY}
      LOGGED_IN_KEY: ${LOGGED_IN_KEY}
      NONCE_KEY: ${NONCE_KEY}
      AUTH_SALT: ${AUTH_SALT}
      SECURE_AUTH_SALT: ${SECURE_AUTH_SALT}
      LOGGED_IN_SALT: ${LOGGED_IN_SALT}
      NONCE_SALT: ${NONCE_SALT}
      MY_KEY: ${MY_KEY}
      WP_DEBUG: ${WP_DEBUG}
  db:
    image: mysql:5
    env_file: .env.docker
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./site/db:/var/lib/mysql
      - ./site/sockets:/var/run/mysqld
