version: '3'
services:
  web:
    image: nginx:1.17
    depends_on:
      - wordpress
      - db
    ports:
      - '7000:80'
    volumes:
      - ./site/www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  wordpress:
    build:
      context: .
      args:
        github_token: ${GITHUB_TOKEN:?err}
    container_name: wordpress
    depends_on:
      - db
    volumes:
      - ./site/www:/var/www/html
    env_file:
      - wordpress.env
  db:
    image: mysql-server:8
    env_file:
      - mysql.env

    volumes:
      - ./site/db:/var/lib/mysql
