version: '3'
services:
  web:
    image: nginx:1.17
    ports:
      - '7000:80'
    volumes:
      - ./code:/code
      - ./conf/site.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:fpm
    volumes:
      - ./conf/scripts:/scripts
      - ./code:/code
  db:
    image: mysql:8
    volumes:
      - ./data/db:/var/lib/mysql
