version: '3'
services:
  web:
    image: nginx:1.17
    depends_on:
      - wordpress
      - db
    ports:
      - '7000:80'
    volumes:
      - ./site/www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  wordpress:
    build:
      context: .
      args:
        github_token: ${GITHUB_TOKEN:?err}
    container_name: wordpress
    depends_on:
      - db
    volumes:
      - ./site/www:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpres
    volumes:
      - ./site/db:/var/lib/mysql
