version: '3'
services:
  web:
    image: nginx:1.17
    depends_on:
      - wordpress
      - db
    ports:
      - '7000:80'
    volumes:
      - ./site/www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  wordpress:
    build:
      context: .
      args:
        github_token: ${GITHUB_TOKEN:?err}
    container_name: wordpress
    depends_on:
      - db
    volumes:
      - ./site/www:/var/www/html
      - ./site/sockets:/var/run/mysqld
    environment:
      WORDPRESS_DB_HOST: localhost:/var/run/mysqld/mysqld.sock
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      AUTH_KEY: c3def60d6b870cb9ddfd5a37e5cc4cb2
      SECURE_AUTH_KEY: a8ee42c175b2b516d1f81ff992db030b
      LOGGED_IN_KEY: bcedc450f8481e89b1445069acdc3dd9
      NONCE_KEY: cb584e44c43ed6bd0bc2d9c7e242837d
      AUTH_SALT: 22b938073218c4d8f0f10a3d36d352b8
      SECURE_AUTH_SALT: 4e3baa46296d1358ea19f237ee1a5d19
      LOGGED_IN_SALT: 1321b53ca4bc07e4d53fa198e59af3e7
      NONCE_SALT: 283a64ff44db59568cc77dba8196046b
      MY_KEY: 5931acc50be4d738a0f530dc4709d155
      WP_DEBUG: 'true'
  db:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./site/db:/var/lib/mysql
      - ./site/sockets:/var/run/mysqld
