version: '3'
services:
  web:
    depends_on:
      - wordpress
    image: nginx:1.17
    ports:
      - '7000:80'
    volumes:
      - ./code:/code
      - ./code/site.conf:/etc/nginx/conf.d/default.conf
  wordpress:
    depends_on:
      - db
    build: .
    image: php-fpm
    volumes:
      - ./code:/code
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./data/db:/var/lib/mysql
