version: '3'
services:
  web:
    image: nginx:1.17
    env_file:
      - site.env
    depends_on:
      - wordpress
    ports:
      - '7000:80'
    volumes:
      - ./code:/code
      - ./code/site.conf:/etc/nginx/conf.d/default.conf
  wordpress:
    build:
      context: ./conf
    depends_on:
      - db
    image: php-fpm
    volumes:
      - ./code:/code
    env_file:
      - site.env
    command: 'bash /code/setup_composer.sh'
  db:
    image: mysql:8
    env_file:
      - site.env
    volumes:
      - ./code/data/db:/var/lib/mysql
